feat: deleting records
FlatFilers/Guides pull request #875
Opened 2023-10-11 22:18 UTC by carlbrugger

2023-10-13 03:38 UTC, brentkulwicki approved these changes

2023-10-15 19:02 UTC, ashleygmulligan2 requested changes

2023-10-15 19:02 UTC, ashleygmulligan2 commented on guides/handling-data.mdx
> +For clearing an entire sheet of its records, set up a bulk delete job. This task will comprehensively wipe out every record on the specified sheet.
link to learn more about jobs

2023-10-15 19:02 UTC, ashleygmulligan2 commented on guides/handling-data.mdx
> +To delete a subset of records, you can use `api.records.delete`. This method takes in an array of record IDs and deletes them from the sheet.
using @flatfile/api - probably need to first say to import this package

2023-10-25 18:38 UTC, ashleygmulligan2 approved these changes

2023-10-25 18:41 UTC, merged