Add estimatedCompletionAt to job acknowledgements in Actions Guide
FlatFilers/Guides pull request #901
Opened 2023-10-20 17:55 UTC by madaley1

2023-10-25 22:29 UTC, ashleygmulligan2 requested changes
Can we also add this parameter to the concepts actions page too?

2023-10-30 19:02 UTC, madaley1 commented
> Can we also add this parameter to the concepts actions page too?

This should be fixed now!

2023-11-02 14:06 UTC, dboskovic commented
I didn't know this was a thing. @ashleygmulligan2 have we considered and made allowances for the problem of asking people to provide specific time, and the obvious timezone drift that can occur?

A better developer experience may just be to ask for an overall estimate in seconds, rather than asking them to provide a timestamp.

2023-11-06 15:42 UTC, ashleygmulligan2 approved these changes

2023-11-06 15:42 UTC, merged